-- =============================================================================
-- Migration 008: Fix pending_invites INSERT policy + invite_token column type
--
-- 1. The INSERT policy in 005 allowed any enterprise member to insert invites.
--    Only admins and owners should be able to do so.
--
-- 2. invite_token was typed as text. All values are UUIDs generated by
--    crypto.randomUUID() — changing to uuid enforces this at the DB layer.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Fix INSERT policy: restrict to admin / owner roles
-- ---------------------------------------------------------------------------
DROP POLICY IF EXISTS "enterprise members can insert pending invites" ON public.pending_invites;

CREATE POLICY "enterprise admins can insert pending invites"
  ON public.pending_invites FOR INSERT
  WITH CHECK (
    enterprise_id IN (SELECT public.get_my_enterprise_ids())
    AND EXISTS (
      SELECT 1 FROM public.enterprise_members
      WHERE user_id = auth.uid()
        AND enterprise_id = pending_invites.enterprise_id
        AND role IN ('admin', 'owner')
    )
  );

-- ---------------------------------------------------------------------------
-- Change invite_token from text to uuid
-- All existing values were generated by crypto.randomUUID() so the cast is safe.
-- ---------------------------------------------------------------------------
ALTER TABLE public.pending_invites
  ALTER COLUMN invite_token TYPE uuid USING invite_token::uuid;
